package com.gnovoa.football.events;

public enum FootballEventType {
    KICK_OFF, HALF_TIME, SECOND_HALF_KICK_OFF, FULL_TIME,
    GOAL, OWN_GOAL,
    PENALTY_AWARDED, PENALTY_SCORED, PENALTY_MISSED, PENALTY_SAVED,
    YELLOW_CARD, SECOND_YELLOW, RED_CARD,
    SUBSTITUTION, INJURY_STOPPAGE,
    VAR_CHECK, VAR_OVERTURNED,
    CORNER_KICK, OFFSIDE,
    SHOT_ON_TARGET, SHOT_OFF_TARGET, SAVE,
    MATCH_SNAPSHOT
}